name: sovendus_banner
description: Official Sovendus Checkout Benefits & Voucher Network plugin for FLutter
version: 1.0.0
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sovendus.banner
        pluginClass: SovendusBanner
      ios:
        pluginClass: SovendusBanner